name: Build Action

on:
  push:
    branches: [main, dev]
    tags: ['v*']
    paths:
      - '**.java'
      - '**.kt'
      - '*.gradle.kts'
      - '**[Dd]ocker*'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [main, dev]
    paths:
      - '**.java'
      - '**.kt'
      - '*.gradle.kts'
      - '**[Dd]ocker*'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      upload-artifact:
        description: 'Upload artifact'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/v')}}

env:
  UPLOAD_ARTIFACT: ${{ github.event.inputs.upload-artifact || false }}

jobs:
  build:
    name: Build - Standalone
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: true
      matrix:
        java-version: [21]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
        with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # ratchet:gradle/actions/setup-gradle@v4

      - name: Build Package
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload artifact
        if: ${{ env.UPLOAD_ARTIFACT == 'true' || startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # ratchet:actions/upload-artifact@v4
        with:
          name: OmniFlow
          path: ./build/libs/*.jar
          if-no-files-found: error
